### ISSUE TITLE
US 10 - create sub-project

### ISSUE THREAD

**Issue by esralund01** [Aluna0001/EksamenKEA#12]
As a manager I want to be able to create sub projects so that I can create a better overview on how to approach a project.

Accept criteria:

- User must be able to create sub projects inside a project

**Comment by Aluna0001** [comment]
As a user, I want to be able to create a new sub-project so that I can manage multiple running projects effectively.

- [ ] Add a "Create Sub-Task" button on the homepage.
- [ ] Design a form with necessary input fields (time, duration).
- [ ] Include a "Save" button to submit the form.
- [ ] Create a createSubProject method in the Controller, Service, and Repository layers (@GetMapping).
- [ ] Create a saveNewSubProject method in the Controller, Service, and Repository layers (@PostMapping).
- [ ] Integrate a database (H2 for testing) to store sub-project details.

For testing:
- [ ] Write integration tests using H2 to ensure sub-projects are saved and retrieved correctly.
- [ ] Mock necessary components for isolated testing (if necessarily??).
- [ ] Verify form validation and redirection work as expected.


Acceptance criteria:
- When the "Create Sub-Task" button is pressed, the user is redirected to a form with (relevant price???) fields.
- After filling out the form and pressing "Save," the user sees a message indicating whether the save was successful or failed.
- The createSubProject and saveNewSubProject methods are functional and properly route requests.
- The submitted form data is validated and stored in the database.
- H2 tests confirm the form data is saved to the database correctly.
- Test coverage includes edge cases (like empty fields or invalid data).
